# requirements
reqs: pyreqs

# install python requirements
pyreqs:
	@echo -e '\n--- Installing python requirements for nlp package \n'
	sudo -H pip3 install --upgrade pip
	sudo -H pip2 install --upgrade pip
	sudo -H pip3 install -r requirements_python3.txt
	sudo -H pip2 install -r requirements_python2.txt
